# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0002_courceorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courceorg',
            name='cources_order',
            field=models.CharField(default=0, max_length=50, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courceorg',
            name='students_order',
            field=models.CharField(default=0, max_length=50, verbose_name='学习人数'),
        ),
    ]
