# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usersk',
            new_name='UserAsk',
        ),
    ]
